spring:
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-secret: secret
            provider: demo-provider
            authorization-grant-type: authorization_code
            redirect-uri: http://client:8082/login/oauth2/code/oidc-client
            scope:
              - message.read
        provider:
          demo-provider:
            authorization-uri: http://auth-server:8080/oauth2/authorize
            token-uri: http://auth-server:8080/oauth2/token
            user-info-uri: http://res-server:8081/sso/user
            user-name-attribute: name
  codec:
    log-request-details: true
server:
  port: 8082
logging:
  level:
    root: debug

